"""
Compiler-native Fusion Optimization & Cost Modeling Framework.
Evaluates FusionPlans generated by the Planner domain to determine their profitability
and make realization decisions without mutating the graph.
"""

from .artifacts import (
    FusionOptimizationReport,
    FusionOptimizationStatistics,
    FusionOptimizationDiagnostic,
    FusionOptimizationDecision
)
from .cost_model import FusionCostModel, DefaultFusionCostModel
from .policy import FusionOptimizationPolicy, DefaultFusionPolicy
from .evaluator import FusionEvaluator

__all__ = [
    "FusionOptimizationReport",
    "FusionOptimizationStatistics",
    "FusionOptimizationDiagnostic",
    "FusionOptimizationDecision",
    "FusionCostModel",
    "DefaultFusionCostModel",
    "FusionOptimizationPolicy",
    "DefaultFusionPolicy",
    "FusionEvaluator"
]
