import SwiftUI

extension OMLXTheme {
    public static let cosmicDark = OMLXTheme(
        isDark: true,
        windowBg: OneDesign.Surfaces.dark.window,
        sidebarBg: OneDesign.Surfaces.dark.panel,
        sidebarBorder: OneDesign.Surfaces.dark.border,
        contentBg: OneDesign.Surfaces.dark.window,
        toolbarBg: OneDesign.Surfaces.dark.panel,
        toolbarBorder: OneDesign.Surfaces.dark.border,
        groupBg: OneDesign.Surfaces.dark.card,
        groupBorder: OneDesign.Surfaces.dark.border,
        rowSep: OneDesign.Surfaces.dark.border.opacity(0.6),
        separator: OneDesign.Surfaces.dark.border,
        text: OneDesign.Colors.textPrimaryDark,
        textSecondary: OneDesign.Colors.textSecondaryDark,
        textTertiary: OneDesign.Colors.textMutedDark,
        accent: OneDesign.Colors.goldDark,
        accentSoft: OneDesign.Colors.goldDark.opacity(0.18),
        accentText: Color.black, // Gold needs dark text for premium look and high contrast
        selBg: OneDesign.Colors.blueDark.opacity(0.18),
        hoverBg: OneDesign.Colors.violetDark.opacity(0.08),
        controlBg: OneDesign.Surfaces.dark.control,
        controlBgHover: OneDesign.Surfaces.dark.overlay,
        glassBg: OneDesign.Surfaces.dark.glassTint,
        glassBgStrong: OneDesign.Surfaces.dark.card,
        inputBg: OneDesign.Surfaces.dark.control,
        inputBorder: OneDesign.Surfaces.dark.border,
        inputBorderFocus: OneDesign.Colors.blueDark,
        greenDot: OneDesign.Colors.emeraldDark,
        amberDot: OneDesign.Colors.amberDark,
        redDot: OneDesign.Colors.crimsonDark,
        blueDot: OneDesign.Colors.blueDark,
        codeBg: OneDesign.Surfaces.dark.card,
        warningBg: OneDesign.Colors.amberDark.opacity(0.16),
        warningText: OneDesign.Colors.amberDark,
        successBg: OneDesign.Colors.emeraldDark.opacity(0.16),
        successText: OneDesign.Colors.emeraldDark,
        desktopWashTopLeft: OneDesign.Colors.violetDark.opacity(0.04), // soft violet stardust
        desktopWashBottomRight: OneDesign.Colors.blueDark.opacity(0.04), // soft blue stardust
        desktopWashBase: OneDesign.Surfaces.dark.window,
        groupHighlightTopOpacity: 0.08,
        groupShadowOpacity: 0.08
    )

    public static let cosmicLight = OMLXTheme(
        isDark: false,
        windowBg: OneDesign.Surfaces.light.window,
        sidebarBg: OneDesign.Surfaces.light.panel,
        sidebarBorder: OneDesign.Surfaces.light.border,
        contentBg: OneDesign.Surfaces.light.window,
        toolbarBg: OneDesign.Surfaces.light.panel,
        toolbarBorder: OneDesign.Surfaces.light.border,
        groupBg: OneDesign.Surfaces.light.card,
        groupBorder: OneDesign.Surfaces.light.border,
        rowSep: OneDesign.Surfaces.light.border.opacity(0.6),
        separator: OneDesign.Surfaces.light.border,
        text: OneDesign.Colors.textPrimaryLight,
        textSecondary: OneDesign.Colors.textSecondaryLight,
        textTertiary: OneDesign.Colors.textMutedLight,
        accent: OneDesign.Colors.goldLight,
        accentSoft: OneDesign.Colors.goldLight.opacity(0.16),
        accentText: OneDesign.Colors.stardustWhite, // light mode needs light text on gold background
        selBg: OneDesign.Colors.blueLight.opacity(0.16),
        hoverBg: OneDesign.Colors.violetLight.opacity(0.06),
        controlBg: OneDesign.Surfaces.light.control,
        controlBgHover: OneDesign.Surfaces.light.overlay,
        glassBg: OneDesign.Surfaces.light.glassTint,
        glassBgStrong: OneDesign.Surfaces.light.card,
        inputBg: OneDesign.Surfaces.light.control,
        inputBorder: OneDesign.Surfaces.light.border,
        inputBorderFocus: OneDesign.Colors.blueLight,
        greenDot: OneDesign.Colors.emeraldLight,
        amberDot: OneDesign.Colors.amberLight,
        redDot: OneDesign.Colors.crimsonLight,
        blueDot: OneDesign.Colors.blueLight,
        codeBg: OneDesign.Surfaces.light.card,
        warningBg: OneDesign.Colors.amberLight.opacity(0.14),
        warningText: OneDesign.Colors.amberLight,
        successBg: OneDesign.Colors.emeraldLight.opacity(0.14),
        successText: OneDesign.Colors.emeraldLight,
        desktopWashTopLeft: OneDesign.Colors.violetLight.opacity(0.02),
        desktopWashBottomRight: OneDesign.Colors.blueLight.opacity(0.02),
        desktopWashBase: OneDesign.Surfaces.light.window,
        groupHighlightTopOpacity: 0.35,
        groupShadowOpacity: 0.06
    )
}
