name: 'Setup Python & uv'
description: 'Sets up a specific Python version and installs uv'
inputs:
  python-version:
    description: 'Python version to set up'
    required: true
    default: '3.12'
runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        cache-dependency-glob: "**/uv.lock"
