# SPDX-License-Identifier: Apache-2.0
"""
Diagnostics generated by optimization intelligence.
"""
from dataclasses import dataclass, field
from typing import List, Optional
from enum import Enum
from .cost_models import CostEstimate
from .telemetry import OptimizationTelemetry
from .recommendations import OptimizationRecommendation

class DiagnosticLevel(Enum):
    INFO = "info"
    WARNING = "warning"
    ERROR = "error"
    DEBUG = "debug"

@dataclass(frozen=True)
class OptimizationDiagnostic:
    level: DiagnosticLevel
    message: str
    pass_name: Optional[str] = None
    cost_estimate: Optional[CostEstimate] = None
    telemetry: Optional[OptimizationTelemetry] = None

@dataclass(frozen=True)
class IntelligenceDiagnosticsReport:
    diagnostics: List[OptimizationDiagnostic] = field(default_factory=list)
    recommendations: List[OptimizationRecommendation] = field(default_factory=list)
